import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

import { Bebas_Neue, Foldit, Roboto, Ubuntu } from 'next/font/google';
 
const ubuntuFont = Ubuntu({
  weight: '300',
  subsets: ['latin'],
});
const foldit = Bebas_Neue({
  weight: '400',
  subsets: ['latin'],
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
